name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: pipx run build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
