name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install dependencies
        run: |
          uv tool install --python-preference only-managed --python ${{ matrix.python-version }} --with tox-uv tox

      - name: Run Tox
        run: tox run -e ${{ matrix.python-version }}

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .tox/coverage.${{ matrix.python-version }}.xml
          flags: ${{ matrix.python-version }}
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          fail_ci_if_error: true
